version: '3'
services:
  block1:
    container_name: node_1
    build: .
    image: blockchain
    ports:
      - "5000:5000"

  block2:
    container_name: node_2
    image: blockchain
    command: "/blockchain -port=5001"
    ports:
      - "5001:5001"
